import Head from 'next/head';
import Image from 'next/image';
import cn from 'classnames';
import styles from './Products.module.css';
import { withLayout } from '@/layout/Layout';
import 'react-responsive-carousel/lib/styles/carousel.min.css';
import Link from 'next/link';
import Card from '@/components/Card/Card';
import classNames from 'classnames';

function Products({ posts, className, ...props }: any): JSX.Element {
  return (
    <>
      <Head>
        <title>АумаПриводСервис электроприводы Auma</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.wrapper}>
        <h4 className={styles.title}>Скачать опросный лист</h4>
        <div className={styles.innerWrapper}>
          <div
            className={classNames(styles.screen, styles.backImage)}
            style={{ backgroundImage: 'url(/images/prod1.png)' }}
          >
            <div
              className={classNames(styles.screenInner, styles.linearToLeft)}
            >
              <span className={styles.icon}>
                <Image
                  src={'/images/privod_cards/mnogo.png'}
                  alt="МНОГООБОРОТНЫЕ ПРИВОДЫ"
                  width={120}
                  height={120}
                />
              </span>
              <Link className={styles.link} href={'/mnogo'}>
                <h4>Многооборотные приводы</h4>
              </Link>
              <p style={{ textAlign: 'center', padding: '0', margin: '0' }}>
                Lorem ipsum dolor sit amet consectetur adipisicing elit.
                Reprehenderit reiciendis fuga soluta eos unde molestiae!
              </p>
            </div>
            <div
              className={classNames(styles.screenInner, styles.linearToLeft)}
            >
              <span className={styles.icon}>
                <Image
                  src={'/images/privod_cards/controls.png'}
                  alt="Средства управления"
                  width={120}
                  height={120}
                />
              </span>
              <Link className={styles.link} href={'/controls'}>
                <h4>Средства управления</h4>
              </Link>
              <p style={{ textAlign: 'center', padding: '0', margin: '0' }}>
                Lorem ipsum dolor sit amet consectetur adipisicing elit.
                Reprehenderit reiciendis fuga soluta eos unde molestiae!
              </p>
            </div>
            <div
              className={classNames(styles.screenInner, styles.linearToLeft)}
            >
              <span className={styles.icon}>
                <Image
                  src={'/images/privod_cards/nepoln.png'}
                  alt="Неполнооборотные приводы"
                  width={120}
                  height={120}
                />
              </span>
              <Link className={styles.link} href={'/nepoln'}>
                <h4>Неполнооборотные приводы</h4>
              </Link>

              <p style={{ textAlign: 'center', padding: '0', margin: '0' }}>
                Lorem ipsum dolor sit amet consectetur adipisicing elit.
                Reprehenderit reiciendis fuga soluta eos unde molestiae!
              </p>
            </div>
          </div>
          <div className={styles.screenMiddle}>
            <div
              className={classNames(styles.screenInner, styles.backgroundColor)}
            >
              <span className={styles.icon}>
                <Image
                  src={'/images/privod_cards/pryamo.png'}
                  alt="Прямоходные приводы"
                  width={120}
                  height={120}
                />
              </span>
              <Link className={styles.link} href={'/pryamo'}>
                <h4>Прямоходные приводы</h4>
              </Link>

              <p style={{ textAlign: 'center', padding: '0', margin: '0' }}>
                Lorem ipsum dolor sit amet consectetur adipisicing elit.
                Reprehenderit reiciendis fuga soluta eos unde molestiae!
              </p>
            </div>
            <div
              className={classNames(styles.screenInner, styles.backgroundColor)}
            >
              <span className={styles.icon}>
                <Image
                  src={'/images/privod_cards/rychag_red.png'}
                  alt="Рычажные редукторы"
                  width={120}
                  height={120}
                />
              </span>
              <Link className={styles.link} href={'/rychag_red'}>
                <h4>Рычажные редукторы</h4>
              </Link>

              <p style={{ textAlign: 'center', padding: '0', margin: '0' }}>
                Lorem ipsum dolor sit amet consectetur adipisicing elit.
                Reprehenderit reiciendis fuga soluta eos unde molestiae!
              </p>
            </div>
            <div
              className={classNames(styles.screenInner, styles.backgroundColor)}
            >
              <span className={styles.icon}>
                <Image
                  src={'/images/privod_cards/rychag.png'}
                  alt="Рычажные приводы"
                  width={120}
                  height={120}
                />
              </span>
              <Link className={styles.link} href={'/rychag'}>
                <h4>Рычажные приводы</h4>
              </Link>

              <p style={{ textAlign: 'center', padding: '0', margin: '0' }}>
                Lorem ipsum dolor sit amet consectetur adipisicing elit.
                Reprehenderit reiciendis fuga soluta eos unde molestiae!
              </p>
            </div>
          </div>
          <div
            className={classNames(
              styles.screen,
              styles.screenRight,
              styles.backImage2
            )}
            style={{ backgroundImage: 'url(/images/prod2.png)' }}
          >
            <div
              className={classNames(styles.screenInner, styles.linearToRight)}
            >
              <span className={styles.icon}>
                <Image
                  src={'/images/privod_cards/nepoln_red.png'}
                  alt="Неполнооборотные редукторы"
                  width={120}
                  height={120}
                />
              </span>
              <Link className={styles.link} href={'/nepoln_red'}>
                <h4>Неполнооборотные редукторы</h4>
              </Link>

              <p style={{ textAlign: 'center', padding: '0', margin: '0' }}>
                Lorem ipsum dolor sit amet consectetur adipisicing elit.
                Reprehenderit reiciendis fuga soluta eos unde molestiae!
              </p>
            </div>
            <div
              className={classNames(styles.screenInner, styles.linearToRight)}
            >
              <span className={styles.icon}>
                <Image
                  src={'/images/privod_cards/mnogo_red.png'}
                  alt="Многооборотные редукторы"
                  width={120}
                  height={120}
                />
              </span>
              <Link className={styles.link} href={'/mnogo_red'}>
                <h4>Многооборотные редукторы</h4>
              </Link>

              <p style={{ textAlign: 'center', padding: '0', margin: '0' }}>
                Lorem ipsum dolor sit amet consectetur adipisicing elit.
                Reprehenderit reiciendis fuga soluta eos unde molestiae!
              </p>
            </div>
            <div
              className={classNames(styles.screenInner, styles.linearToRight)}
            >
              <span className={styles.icon}>
                <Image
                  src={'/images/privod_cards/mnogo_red.png'}
                  alt="Многооборотные редукторы"
                  width={120}
                  height={120}
                />
              </span>
              <Link className={styles.link} href={'/mnogo_red'}>
                <h4>Многооборотные редукторы</h4>
              </Link>

              <p style={{ textAlign: 'center', padding: '0', margin: '0' }}>
                Lorem ipsum dolor sit amet consectetur adipisicing elit.
                Reprehenderit reiciendis fuga soluta eos unde molestiae!
              </p>
            </div>
          </div>
        </div>
      </div>
    </>
  );
}

export default withLayout(Products);
