import Head from 'next/head';
import Image from 'next/image';
import cn from 'classnames';
import styles from '@/styles/Home.module.css';
import { withLayout } from '@/layout/Layout';
import { Carousel } from 'react-responsive-carousel';
// import Carousel from 'react-responsive-carousel/lib/js/components/Carousel/index';
import 'react-responsive-carousel/lib/styles/carousel.min.css';
import {
  AnimationHandler,
  AnimationHandlerResponse,
} from 'react-responsive-carousel/lib/ts/components/Carousel/types';
import Card from '@/components/Card/Card';

const imagesCarousel = [
  '/images/111.png',
  '/images/222.png',
  '/images/333.png',
  '/images/444.png',
  '/images/555.png',
  '/images/777.png',
];

function Home({ posts, className, ...props }: any): JSX.Element {
  return (
    <>
      <Head>
        <title>АумаПриводСервис электроприводы Auma</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={cn(className, styles.bodyWrapper)} {...props}>
        <div className={styles.bodyLeft}>
          <Card type="privod" icon="mnogo">
            Многооборотные приводы
          </Card>
          <Card type="privod" icon="controls">
            Средства управления
          </Card>
        </div>
        <div className={styles.bodyCenter}>
          <Carousel
            useKeyboardArrows={true}
            showArrows={false}
            showStatus={false}
            autoPlay={true}
            infiniteLoop={true}
            interval={10000}
            animationHandler={fadeAnimationHandler}
            showThumbs={false}
            swipeable={false}
          >
            {imagesCarousel.map((URL, index) => (
              <div className={styles.slideMain} key={index}>
                {/* <div className={styles.sliderText}>
                Lorem ipsum dolor sit amet consectetur, adipisicing elit.
                Sapiente similique dolor cumque fuga incidunt reiciendis
                corporis laborum voluptate vel sequi architecto, veniam iste et
                at blanditiis debitis earum neque? Saepe.
              </div> */}
                <Image
                  src={URL}
                  alt="фото сфер деятельности компании"
                  fill
                  // width={100}
                  // height={450}
                  quality={100}
                  className={styles.image}
                />
              </div>
            ))}
          </Carousel>
        </div>
        <div className={styles.bodyRight}>
          <Card type="privod" icon="nepoln">
            Неполнооборотные приводы
          </Card>
          <Card type="privod" icon="pryamo">
            Прямоходные приводы
          </Card>
        </div>
      </div>
      <div className={styles.cards}>
        <Card type="privod" icon="rychag_red">
          Рычажные редукторы
        </Card>
        <Card type="privod" icon="rychag">
          Рычажные приводы
        </Card>
        <Card type="privod" icon="nepoln_red">
          Неполнооборотные редукторы
        </Card>
        <Card type="privod" icon="mnogo_red">
          Многооборотные редукторы
        </Card>
      </div>
      <div className={styles.bodyInner}>
        <div className={styles.bodyNews}>
          <h4
            style={{
              fontSize: '1.2rem',
              margin: '0',
              textTransform: 'uppercase',
            }}
          >
            Новости
          </h4>
          {posts &&
            posts.map((post: Post) => (
              <div key={post.id} className={styles.newsTitleWrapper}>
                <h5 className={styles.newsTitle1}>
                  <Link href={`/news/${post.id}`}>
                    {post.titleShort ? post.titleShort : post.title}
                  </Link>
                </h5>
                <span>{post.dateString}</span>
              </div>
            ))}
        </div>
        <div className={styles.bodyCompany}>
          <p className={styles.textMain}>
            ООО «АумаПриводСервис» представляет на Российском рынке оборудование
            фирмы AUMA Riester GmbH (Германия) - мирового лидера в производстве
            электроприводов и средств управления запорно-регулирующей арматурой.
          </p>
          <p className={styles.text}>
            Многолетний опыт работы с российскими и зарубежными производителями
            арматуры позволяет комплектовать оборудованием AUMA все типы
            исполнительных устройств. Для быстрого подбора существуют типовые
            таблицы комплектации с арматурой. Оборудование имеет модульную
            конструкцию, которая позволяет оптимально приспосабливать приводы к
            конкретным условиям эксплуатации.
          </p>
          <p className={styles.text}>
            Продукция компании «AUMA» имеет высокий уровень технического
            оснащения и соответствует международно-признанным стандартам
            качества. При этом ценовая политика для крупных потребителей
            позволяет выдерживать уровень цен конкурентный с российской
            продукцией.
          </p>
        </div>
      </div>
    </>
  );
}

export default withLayout(Home);

const fadeAnimationHandler: AnimationHandler = (
  props,
  state
): AnimationHandlerResponse => {
  const transitionTime = props.transitionTime + 'ms';
  const transitionTimingFunction = 'ease-in-out';

  let slideStyle: React.CSSProperties = {
    position: 'absolute',
    display: 'block',
    zIndex: 1,
    minHeight: '100%',
    opacity: 0,
    top: 0,
    right: 0,
    left: 0,
    bottom: 0,
    transitionTimingFunction: transitionTimingFunction,
    msTransitionTimingFunction: transitionTimingFunction,
    MozTransitionTimingFunction: transitionTimingFunction,
    WebkitTransitionTimingFunction: transitionTimingFunction,
    OTransitionTimingFunction: transitionTimingFunction,
  };

  if (!state.swiping) {
    slideStyle = {
      ...slideStyle,
      WebkitTransitionDuration: transitionTime,
      MozTransitionDuration: transitionTime,
      OTransitionDuration: transitionTime,
      transitionDuration: transitionTime,
      msTransitionDuration: transitionTime,
    };
  }

  return {
    slideStyle,
    selectedStyle: { ...slideStyle, opacity: 1, position: 'relative' },
    prevStyle: { ...slideStyle },
  };
};

import fsPromises from 'fs/promises';
import path from 'path';
import { Post, Posts } from '@/interfaces/post.interface';
import Link from 'next/link';
export async function getStaticProps() {
  const filePath = path.join(process.cwd(), 'news.json');
  const jsonData = await fsPromises.readFile(filePath);
  const objectData = await JSON.parse(jsonData.toString());

  let convData = { posts: [] };

  convData.posts = objectData.posts
    .sort((a: Post, b: Post) => {
      return new Date(b.date).getTime() - new Date(a.date).getTime();
    })
    .slice(0, 3);

  return {
    props: convData,
  };
}
