'use client';

/* eslint-disable react/no-unescaped-entities */
import Head from 'next/head';
import Image from 'next/image';
import cn from 'classnames';
import styles from './Contact.module.css';
import { withLayout } from '@/layout/Layout';
// import { YMaps, Map, Placemark } from '@pbe/react-yandex-maps';
import dynamic from 'next/dynamic';

const Surgut = dynamic(() => import('../../components/Maps/Surgut'), {
  ssr: false,
});
const Omsk = dynamic(() => import('../../components/Maps/Omsk'), {
  ssr: false,
});
const Irkutsk = dynamic(() => import('../../components/Maps/Irkutsk'), {
  ssr: false,
});

function Contacts() {
  return (
    <>
      <Head>
        <title>АумаПриводСервис электроприводы АУМА</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={cn(styles.innerWrapper, styles.surgut)}>
        <h4 className={styles.header}>ООО «АумаПриводСервис»</h4>
        <div className={styles.address}>
          628404, ХМАО-Югра, г. Сургут, ул. Рационализаторов, д.23/2
        </div>
        <div className={styles.tel}>
          <strong>Тел./Факс:</strong> (3462) 236-234, 236-299
        </div>
        <div className={styles.email}>
          <strong>E-mail:</strong> auma@aumaprivod.ru
        </div>
        <div className={styles.map}>
          {/* <YMaps>
              <Map
                defaultState={{
                  center: [61.24800656236425, 73.4841845],
                  zoom: 15,
                }}
                width="400px"
                height="300px"
              >
                <Placemark geometry={[61.24800656236425, 73.4841845]} />
              </Map>
            </YMaps> */}

          <div suppressHydrationWarning>
            {typeof window !== 'undefined' && (
              <Surgut />
              // <YMaps>
              //   <Map
              //     defaultState={{
              //       center: [61.24800656236425, 73.4841845],
              //       zoom: 15,
              //     }}
              //     width="400px"
              //     height="300px"
              //   >
              //     <Placemark geometry={[61.24800656236425, 73.4841845]} />
              //   </Map>
              // </YMaps>
            )}
          </div>
          {/* <a
              href="https://yandex.com/maps/?um=constructor%3A9eb300ee438b407ddcbe609b84c0104937c914f9ef5a5ff4c401295d8b300da7&amp;source=constructorStatic"
              target="_blank"
            >
              <img
                src="https://api-maps.yandex.ru/services/constructor/1.0/static/?um=constructor%3A9eb300ee438b407ddcbe609b84c0104937c914f9ef5a5ff4c401295d8b300da7&amp;width=400&amp;height=300&amp;lang=en_FR"
                alt=""
                // style="border: 0;"
              />
            </a> */}
        </div>
      </div>
      <div className={styles.wrapper}>
        <div className={styles.innerWrapper}>
          <h4 className={styles.header}>
            Обособленное подразделение ООО «АумаПриводСервис»&nbsp;г.&nbsp;Иркутск
          </h4>
          <div className={styles.address}>
            664009, г.&nbsp;Иркутск, улица Советская, дом 109, офис 313 Б
          </div>
          <div className={styles.tel}>
            <strong>Тел.:</strong> (3952) 27-01-87, 27-01-89, 99-87-93
          </div>
          <div className={styles.email}>
            <strong>E-mail:</strong> auma@aumaprivod.ru
          </div>
          <div className={styles.map}>
            {/* <a
              href="https://yandex.com/maps/?um=constructor%3Aa0e3830ac4ead1444ab07d292eba01dc73efb9c8b8c9a8009b2b8bf37799ed02&amp;source=constructorStatic"
              target="_blank"
            >
              <img
                src="https://api-maps.yandex.ru/services/constructor/1.0/static/?um=constructor%3Aa0e3830ac4ead1444ab07d292eba01dc73efb9c8b8c9a8009b2b8bf37799ed02&amp;width=400&amp;height=300&amp;lang=en_FR"
                alt=""
                // style="border: 0;"
              />
            </a> */}
            <div suppressHydrationWarning>
              {typeof window !== 'undefined' && (
                <Irkutsk />
                // <YMaps suppressHydrationWarning>
                //   <Map
                //     defaultState={{
                //       center: [52.280216571867705, 104.33866449999998],
                //       zoom: 15,
                //     }}
                //     width="400px"
                //     height="300px"
                //   >
                //     <Placemark
                //       geometry={[52.280216571867705, 104.33866449999998]}
                //     />
                //   </Map>
                // </YMaps>
              )}
            </div>

            {/* <iframe
              src="https://yandex.ru/map-widget/v1/?um=constructor%3Aa0e3830ac4ead1444ab07d292eba01dc73efb9c8b8c9a8009b2b8bf37799ed02&amp;source=constructor"
              width="400"
              height="300"
              frameBorder="0"
            ></iframe> */}
          </div>
        </div>
        <div className={styles.innerWrapper}>
          <h4 className={styles.header}>
            Обособленное подразделение ООО «АумаПриводСервис»&nbsp;г.&nbsp;Омск
          </h4>
          <div className={styles.address}>
            644123, г.&nbsp;Омск, ул.70 Лет Октября, 24, офис 410
          </div>
          <div className={styles.tel}>
            <strong>Тел.:</strong> (3812) 700-012
          </div>
          <div className={styles.email}>
            <strong>E-mail:</strong> auma@aumaprivod.ru
          </div>
          <div className={styles.map}>
            {/* <a
              href="https://yandex.com/maps/?um=constructor%3Add560a00ffec987ce0ff0d53cf7d213976b4367b6738ca37f7a86d7d9226bc5d&amp;source=constructorStatic"
              target="_blank"
            >
              <img
                src="https://api-maps.yandex.ru/services/constructor/1.0/static/?um=constructor%3Add560a00ffec987ce0ff0d53cf7d213976b4367b6738ca37f7a86d7d9226bc5d&amp;width=400&amp;height=300&amp;lang=en_FR"
                alt=""
                // style="border: 0;"
              />
            </a> */}

            <div suppressHydrationWarning>
              {typeof window !== 'undefined' && (
                <Omsk />
                // <YMaps suppressHydrationWarning>
                //   <Map
                //     defaultState={{
                //       center: [54.98154606971653, 73.32319749999995],
                //       zoom: 15,
                //     }}
                //     width="400px"
                //     height="300px"
                //   >
                //     <Placemark
                //       geometry={[54.98154606971653, 73.32319749999995]}
                //     />
                //   </Map>
                // </YMaps>
              )}
            </div>
            {/* <iframe
              src="https://yandex.ru/map-widget/v1/?um=constructor%3Add560a00ffec987ce0ff0d53cf7d213976b4367b6738ca37f7a86d7d9226bc5d&amp;source=constructor"
              width="400"
              height="300"
              frameBorder="0"
            ></iframe> */}
          </div>
        </div>
      </div>
    </>
  );
}

export default withLayout(Contacts);
